name: Quarkus Deploy Snapshots

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
jobs:
  build-and-deploy:
    name: "Build and deploy"
    runs-on: ubuntu-22.04
    if: github.repository == 'quarkusio/quarkus'
    env:
      MAVEN_OPTS: -Xmx2048m -XX:MaxMetaspaceSize=1000m
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: deploy-snapshots-${{ steps.get-date.outputs.date }}
      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          ./mvnw -e -B --settings .github/release-settings.xml \
            -Dnjord.autoPublish \
            -DskipTests -DskipITs -Dno-format -Dinvoker.skip=true \
            -Dno-test-modules \
            -Dgradle.cache.local.enabled=false \
            -Ddokka \
            -DskipDocs \
            clean deploy
      - name: Delete Local Artifacts From Cache
        shell: bash
        run: rm -r ~/.m2/repository/io/quarkus

      - name: Report
        if: always()
        shell: bash
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          ~/.jbang/bin/jbang .github/NativeBuildReport.java \
            issueNumber=12111 \
            runId=${{ github.run_id }} \
            status=${{ job.status }} \
            token=${{ secrets.GITHUB_API_TOKEN }} \
            issueRepo=${{ github.repository }} \
            thisRepo=${{ github.repository }}
